version: '3'
services:
  catalog-api:
    build: ./catalogItemAPI
    ports:
      - "8000:8000"
    volumes:
      - ./catalogItemAPI:/app
    depends_on:
      - catalog-db
  catalog-storefront-api:
    build: ./catalogStorefrontAPI
    ports:
      - "8001:8000"
    volumes:
      - ./catalogStorefrontAPI:/app
    depends_on:
      - catalog-db
  catalog-db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - catalog-db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=catalog
  cart-api:
    build: ./cartAPI
    ports:
      - "8002:8000"
    volumes:
      - ./cartAPI:/app
    depends_on:
      - cart-db
  cart-db:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - cart-db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=cart
  user-api:
    build: ./userAPI
    ports:
      - "8003:8000"
    volumes:
      - ./userAPI:/app
    depends_on:
      - user-db
  user-db:
    image: mongo
    ports:
      - "27019:27017"
    volumes:
      - user-db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=user

volumes:
  catalog-db-data:
  cart-db-data:
  user-db-data:
