version: '3'
services:
  catalog-api:
    container_name: catalog-api
    build: ./catalogItemAPI
    # ports:
    #   - "8000:8000"
    volumes:
      - ./catalogItemAPI:/app
    depends_on:
      - catalog-db
      - eureka
  catalog-storefront-api:
    container_name: catalog-storefront-api
    build: ./catalogStorefrontAPI
    # ports:
    #   - "8001:8000"
    volumes:
      - ./catalogStorefrontAPI:/app
    depends_on:
      - catalog-db
      - eureka
  catalog-db:
    container_name: catalog-db
    image: mongo
    # ports:
    #   - "27017:27017"
    volumes:
      - catalog-db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=catalog
  cart-api:
    container_name: cart-api
    build: ./cartAPI
    # ports:
    #   - "8002:8000"
    volumes:
      - ./cartAPI:/app
    depends_on:
      - cart-db
      - eureka
  cart-db:
    container_name: cart-db
    image: mongo
    # ports:
    #   - "27018:27017"
    volumes:
      - cart-db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=cart
  user-api:
    container_name: user-api
    build: ./userAPI
    # ports:
    #   - "8003:8000"
    volumes:
      - ./userAPI:/app
    depends_on:
      - user-db
      - eureka
  user-db:
    container_name: user-db
    image: mongo
    # ports:
    #   - "27019:27017"
    volumes:
      - user-db-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=user
  gateway:
    container_name: gateway
    image: nginx
    ports:
      - "80:80"
  eureka:
    container_name: eureka
    image: steeltoeoss/eureka-server:latest
    ports:
      - "8761:8761"

volumes:
  catalog-db-data:
  cart-db-data:
  user-db-data:
